title: "Martin Sasieta"
description: "Quantum gravity & high‑energy theory"
# Built-in GitHub Pages theme
remote_theme: jekyll/minima

# Site-wide settings
url: "https://msasieta.github.io"   # ← change to your username site or custom domain
baseurl: ""                                 # keep empty for user site

google_site_verification: "shE0rvKqTEqGRHXvdzaDod0sHekIfbF9MUmkQsUTCw4"
google_analytics: G-12169100719

# Minima theme options
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { title: "Email",           icon: "envelope",        style: "solid",  url: "mailto:msasieta@berkeley.edu" }
    - { title: "Google Scholar",  icon: "graduation-cap",  style: "solid",  url: "https://scholar.google.com/citations?user=ZKwaV5cAAAAJ" }
    - { title: "ORCID",           icon: "orcid",           style: "brands", url: "https://orcid.org/0000-0003-1056-6000" }
    - { title: "arXiv",           icon: "archive",         style: "solid",  url: "https://arxiv.org/search/hep-th?searchtype=author&query=Sasieta,+M" }
    - { title: "X / Twitter",     icon: "x-twitter",       style: "brands", url: "https://x.com/martinsasieta" }
    - { title: "INSPIRE HEP",     icon: "book",            style: "solid",  url: "https://inspirehep.net/authors/1739705?ui-citation-summary=true" }  
    
# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Navigation: which pages appear in the header
header_pages:
  - about.md
  - research.md
  - publications.md
  - talks.md
  - teaching.md
  - cv.md

# Plugins that are whitelisted on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Both are supported on GitHub Pages; if you ever build locally, these help RSS & SEO.
