title: "Martin Sasieta"
description: "Quantum gravity & high‑energy theory"
# Built-in GitHub Pages theme
remote_theme: jekyll/minima

# Site-wide settings
url: "https://msasieta.github.io"   # ← change to your username site or custom domain
baseurl: ""                                 # keep empty for user site

google_site_verification: "shE0rvKqTEqGRHXvdzaDod0sHekIfbF9MUmkQsUTCw4"
google_analytics: G-12169100719

# Minima theme options
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: email,  user_url: "mailto:msasieta@berkeley.edu" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=XXXXX" }
    - { platform: orcid, user_url: "https://orcid.org/0000-0000-0000-0000" }
    - { platform: arxiv, user_url: "https://arxiv.org/a/lastname_m_1.html" }
    - { platform: x, user_url: "https://x.com/<handle>" }

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Navigation: which pages appear in the header
header_pages:
  - about.md
  - research.md
  - publications.md
  - talks.md
  - teaching.md
  - cv.md

# Plugins that are whitelisted on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Both are supported on GitHub Pages; if you ever build locally, these help RSS & SEO.
